import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Homee from '../pages/home'
import Classifies from '../../Component/classify/Classifies'
import MostPop from '../../Component/Card/MostPop'
import YellowCom from '../../Component/yellowPage/YellowCom'
import PopularElem from '../../Component/CardStyle2/PopularElem'
import Earn from '../../Component/Earn/Earn'
import Comment from '../../Component/comment/Comment'



export default function Home() {
  return (
    <>
      <Head>
        <title>daliluna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
       <Homee/>
      <Classifies/>
      <MostPop/>
      <YellowCom/>
      <PopularElem/>
      <Earn/>
      <Comment/>
   
      </main>
    </>
  )
}


